services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: penguins_classifier
    env_file:
      - ${ENV_FILE:-.env.dev}
    environment:
      - ENV=${ENV}
    ports:
      - "${APP_PORT}:8000"
    volumes:
      - .:/app
    command: >
      sh -c "
      if [ \"$ENV\" = \"dev\" ]; then
        uvicorn main:app --host 0.0.0.0 --port 8000 --reload;
      else
        uvicorn main:app --host 0.0.0.0 --port 8000;
      fi
      "