name: Docker Publish

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  bump_version:
    name: Bump Version Automatically
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.bump.outputs.version }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install standard-version
        run: npm install -g standard-version

      - name: Bump version using conventional commits
        id: bump
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          version=$(standard-version --dry-run | grep "tagging release" | awk '{print $NF}')
          echo "New version: $version"
          echo "version=$version" >> $GITHUB_OUTPUT
          standard-version

      - name: Push tag and changelog
        run: |
          git push --follow-tags origin main

  build:
    name: Build Python Project
    needs: bump_version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  dockerize:
    name: Dockerize and Push Image
    needs: [build, bump_version]  # Waits for both to finish
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
  
      - name: Build Docker image
        run: |
          docker build -t penguis_classifier-app .
  
      - name: Tag Docker image
        run: |
          TAG=${{ needs.bump_version.outputs.new_version }}
          echo "Tagging image with version: $TAG"
          docker tag penguis_classifier-app slimcent/penguin_classifier:$TAG
          docker tag penguis_classifier-app slimcent/penguin_classifier:latest
  
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
  
      - name: Push Docker image to Docker Hub
        run: |
          TAG=${{ needs.bump_version.outputs.new_version }}
          echo "Pushing Docker image with tag: $TAG"
          docker push slimcent/penguin_classifier:$TAG
          docker push slimcent/penguin_classifier:latest
