name: Docker Publish

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  bump_version:
    name: Bump Version Automatically
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.bump.outputs.version }}  # Correct output assignment
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install standard-version
        run: npm install -g standard-version

      - name: Bump version using conventional commits
        id: bump
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          version=$(standard-version --dry-run | grep "tagging release" | awk '{print $NF}')
          standard-version
          echo "version=$version" >> $GITHUB_ENV   # Use $GITHUB_ENV to pass the version as environment variable

      - name: Push tag and changelog
        run: |
          git push --follow-tags origin main

  build:
    name: Build Python Project
    needs: bump_version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  docker_build:
    name: Build Docker Image
    needs: bump_version  # Ensure it depends on bump_version job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Debug Version
        run: |
          echo "Version tag: ${{ needs.bump_version.outputs.new_version }}"  # Access the output from bump_version job

      - name: Build Docker image
        run: |
          echo "Building Docker image with version: ${{ needs.bump_version.outputs.new_version }}"
          docker build -t slimcent/penguin_classifier:${{ needs.bump_version.outputs.new_version }} .
          docker tag slimcent/penguin_classifier:${{ needs.bump_version.outputs.new_version }} slimcent/penguin_classifier:latest

  docker_push:
    name: Push Docker Image
    needs: docker_build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          echo "Pushing Docker image to Docker Hub"
          docker push slimcent/penguin_classifier:${{ needs.bump_version.outputs.new_version }}
          docker push slimcent/penguin_classifier:latest
